### ISSUE TITLE
How to install and use

### ISSUE THREAD

**Issue by josephmiller2000** [NabiKAZ/video2gif#2]
How to install it and use it in windows? I'm quite confused by your short information on the page. Can you provide the step by step procedure, how to do this?

**Comment by NabiKAZ** [comment]
Thanks for use this program.
The steps to install and use are clearly explained in this link: https://github.com/NabiKAZ/video2gif/blob/master/README.md
You do not need to install a specific one. You just need to download and define the ffmpeg and video2gif in your PATH of windows and then run it as cmd.
Is there a particular problem?
