### ISSUE TITLE
stream video from decklink input

### ISSUE THREAD

**Issue by sfahadshahzad** [NabiKAZ/video2gif#5]
Hi,

Hope you are doing well and keeping safe.

I want create batch file for ffmpeg to get video input from decklink and output to udp as mpegts

here is sample command;

.\ffmpeg.exe -f decklink -i 48:00000000:00300a00 -c:v libx264 -tune zerolatency -preset:v veryfast -x264opts bitrate=6000:vbv-maxrate=6000:vbv-bufsize=5000:ratetol=200:vbv-init=200 -pix_fmt yuv420p -bf 3 -b_strategy 1 -crf 18 -profile:v high -level:v 4.1 -r 25.00 -g 60 -s 1920x1080 -aspect 16:9 -b:v 6M -minrate 6M -maxrate 6M -bufsize 3M -c:a libfdk_aac -b:a 128000 -ar 44100 -ac 2 -mpegts_flags resend_headers -f mpegts -muxrate 7000k -x264-params interlaced=1 -sc_threshold 500 udp://239.253.253.4:1234?pkt_size=1316

Regards,

Fahad

**Comment by NabiKAZ** [comment]
Hello and thanks for your message.
I think this issue is not related to this project.
Anyway, I did not understand what you mean, but if your input and output and command are fixed, you can save and run it in a bat file. no problem.
